# Using finally keyword

# try:
#     file = open(exceptional_handling_2.py)
#     age = int(input("Enter age :"))
#     fact = 10/age
# except(NameError, ValueError, ZeroDivisionError):
#     print("An Error Occured...")
# finally:
#     file.close()
# Closing file is important so to make
# sure that it got closed we pass it in finally to make
# sure it will got executed even their is no error or error
